# -*- coding: utf-8 -*-
"""aplicacion_app

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OTStlWaZV2rgYgc2hm7iVIzlWUHeegP8
"""

# Importamos las librerias
import streamlit as st
import pandas as pd

# Commented out IPython magic to ensure Python compatibility.
# %pip install streamlit

# Importamos las librerias
import streamlit as st
import pandas as pd
import yfinance as yf

st.title("Mi primera aplicacion en Streamlit <3")

#lista de ticker inicial
lista_tickers=["APPL", "MSFT", "NVDA", "META"]

#Multiselector
ticker=st.multoselect("Elija un ticker o varios", lista_tickers)

#Boton
if st.button("Descargar"):
    data=yf.download(ticker,period="1mo")[close]
    st.subheader(precio de cierres)
    st.write(data)

