# -*- coding: utf-8 -*-
"""aplicacion_app

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OTStlWaZV2rgYgc2hm7iVIzlWUHeegP8
"""

# Importamos las librerias
import streamlit as st
import pandas as pd

# Commented out IPython magic to ensure Python compatibility.
# %pip install streamlit

# Importamos las librerias
import streamlit as st
import pandas as pd

st.title("Mi primera aplicacion en Streamlit <3")