# -*- coding: utf-8 -*-
"""Gestion_de_portafolio_de_inversion

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19hNYLQ18XlfJGcfm44l3mm-_2SsqMj0j
"""

# Commented out IPython magic to ensure Python compatibility.
# %pip install streamlit
#TALLER: GESTIÓN DE PORTAFOLIOS DE INVERSIÓN
# Estudiante: Angie, Dayana y Jhony
# Evaluación de listas, tuplas, diccionarios, ciclos y condicionales
#
# PARTE 1: DECLARACIÓN DE VARIABLES Y LISTAS
#

# Datos iniciales
clientes = ["Juan Perez", "Maria Rodriguez", "Carlos Lopez", "Ana Gomez"]
montos_invertidos = [10000, 15000, 20000, 18000]
rendimientos = [5.5, 6.0, 4.0, 7.5]

# Crear tuplas para cada cliente
cliente_1 = (clientes[0], montos_invertidos[0], rendimientos[0])
cliente_2 = (clientes[1], montos_invertidos[1], rendimientos[1])
cliente_3 = (clientes[2], montos_invertidos[2], rendimientos[2])
cliente_4 = (clientes[3], montos_invertidos[3], rendimientos[3])

# Mostrar las tuplas (solo para verificación)
print("=== Tuplas de Clientes ===")
print(cliente_1)
print(cliente_2)
print(cliente_3)
print(cliente_4)
print()  # línea en blanco



# PARTE 2: USO DE DICCIONARIOS Y CONDICIONALES


# Crear el diccionario portafolio
portafolio = {
    "Juan Perez": {"monto_invertido": 10000, "rendimiento": 5.5},
    "Maria Rodriguez": {"monto_invertido": 15000, "rendimiento": 6.0},
    "Carlos Lopez": {"monto_invertido": 20000, "rendimiento": 4.0},
    "Ana Gomez": {"monto_invertido": 18000, "rendimiento": 7.5}
}

# Imprimir clientes con rendimiento superior al 5%
print("=== Clientes con rendimiento superior al 5% ===")
for cliente, datos in portafolio.items():
    if datos["rendimiento"] > 5:
        print(f"{cliente} tiene un rendimiento de {datos['rendimiento']}%")
print()



# PARTE 3: CÁLCULOS CON CICLOS


# Calcular el rendimiento total del portafolio
rendimiento_total = 0

for cliente, datos in portafolio.items():
    rendimiento_cliente = (datos["monto_invertido"] * datos["rendimiento"]) / 100
    rendimiento_total += rendimiento_cliente

print(f"El rendimiento total del portafolio es: ${rendimiento_total:.2f}")
print()

# Identificar el cliente con mayor rendimiento absoluto
mayor_rendimiento = 0
cliente_top = ""

for cliente, datos in portafolio.items():
    rendimiento_cliente = (datos["monto_invertido"] * datos["rendimiento"]) / 100
    if rendimiento_cliente > mayor_rendimiento:
        mayor_rendimiento = rendimiento_cliente
        cliente_top = cliente

print(f"El cliente con mayor rendimiento es {cliente_top}, con ${mayor_rendimiento:.2f}")
print()



# PARTE 4: MODIFICACIONES DEL PORTAFOLIO

# Actualizar monto de Carlos Lopez
portafolio["Carlos Lopez"]["monto_invertido"] = 25000

# Añadir nuevo cliente Laura Fernandez
portafolio["Laura Fernandez"] = {"monto_invertido": 22000, "rendimiento": 6.8}

# Remover a Ana Gomez
del portafolio["Ana Gomez"]

# Mostrar portafolio actualizado
print("=== Portafolio Actualizado ===")
for cliente, datos in portafolio.items():
    print(f"{cliente}: Monto = ${datos['monto_invertido']}, Rendimiento = {datos['rendimiento']}%")